# shared/connections/database.yaml
name: "Username-Password-Authentication"
strategy: "auth0"
enabled_clients:
  - "SubscribeHub Web Portal"
options:
  password_policy: "good"
  requires_username: false
  brute_force_protection: true
  enable_signup: true
  disable_signup: false
  min_username_length: 3
  max_username_length: 50
  password_complexity_options:
    min_length: 8
  password_history:
    enable: true
    size: 5
  password_no_personal_info:
    enable: true
  password_dictionary:
    enable: true
  mfa:
    active: false